name: Run 20 Docker Jobs

on:
  workflow_dispatch:
  push:

jobs:
  run-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
      max-parallel: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Docker container
        run: |
          docker run --network=host --name=9hits 9hitste/appv5 /nh.sh --token=5a313b569e81ef8082d28c53ecf8e47a --system-session --ex-proxy-sessions=10 --allow-crypto=no --session-note=9hits-pool --note=my-laptop
